name: intl_utils
description: intl_utils is a dart library that generates Dart localization code from ARB file. Generated code relies on Intl library.
version: 12.8.7
homepage: https://github.com/localizely/intl_utils

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  analyzer: ^5.13.0 # no updated for sdk 2.17.0
  archive: ^3.0.0
  args: ^2.0.0
  dart_style: ^2.0.0
  http: ">=0.13.0 <2.0.0"
  intl: ">=0.17.0 <0.20.0"
  path: ^1.8.0
  petitparser: ">=4.0.0 <7.0.0"
  yaml: ^3.0.0
  cryptography: ^2.5.0
  encrypt: 5.0.1

dev_dependencies:
  build_runner: ^2.0.6
  lints: ^2.0.1 # no updated for sdk 2.17.0
  mockito: ^5.4.2 # no updated for sdk 2.17.0
  test: ^1.16.0
